export default {
  namespaced: true,
  state: {
    productsList: [
      {
        id: 1,
        name: 'Seif',
        url: 'https://www.andresrivera.com.co',
        urlImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshenandoahcountyva.us%2Fbos%2Fwp-content%2Fuploads%2Fsites%2F4%2F2018%2F01%2Fpicture-not-available-clipart-12.jpg&f=1&nofb=1',
        module: 'module',
        Category: 'category',
        Entorno: 'entorno',
      },
      {
        id: 2,
        name: 'Seif módulos',
        url: 'https://www.andresrivera.com.co',
        urlImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshenandoahcountyva.us%2Fbos%2Fwp-content%2Fuploads%2Fsites%2F4%2F2018%2F01%2Fpicture-not-available-clipart-12.jpg&f=1&nofb=1',
        module: 'module',
        Category: 'category',
        Entorno: 'entorno',
      },
      {
        id: 3,
        name: 'Seif Controller',
        url: 'https://www.andresrivera.com.co',
        urlImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshenandoahcountyva.us%2Fbos%2Fwp-content%2Fuploads%2Fsites%2F4%2F2018%2F01%2Fpicture-not-available-clipart-12.jpg&f=1&nofb=1',
        module: 'module',
        Category: 'category',
        Entorno: 'entorno',
      },
      {
        id: 4,
        name: 'Visitantes robusto',
        url: 'https://www.andresrivera.com.co',
        urlImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshenandoahcountyva.us%2Fbos%2Fwp-content%2Fuploads%2Fsites%2F4%2F2018%2F01%2Fpicture-not-available-clipart-12.jpg&f=1&nofb=1',
        module: 'module',
        Category: 'category',
        Entorno: 'entorno',
      },
      {
        id: 5,
        name: 'PTT',
        url: 'https://www.andresrivera.com.co',
        urlImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshenandoahcountyva.us%2Fbos%2Fwp-content%2Fuploads%2Fsites%2F4%2F2018%2F01%2Fpicture-not-available-clipart-12.jpg&f=1&nofb=1',
        module: 'module',
        Category: 'category',
        Entorno: 'entorno',
      },
      {
        id: 6,
        name: 'Controlpharm',
        url: 'https://www.andresrivera.com.co',
        urlImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshenandoahcountyva.us%2Fbos%2Fwp-content%2Fuploads%2Fsites%2F4%2F2018%2F01%2Fpicture-not-available-clipart-12.jpg&f=1&nofb=1',
        module: 'module',
        Category: 'category',
        Entorno: 'entorno',
      },
    ],
  },
};
